/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLIENTPLACES_H_RPCGEN
#define _CLIENTPLACES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct place {
	char *name;
	char state[2];
	double lat;
	double lon;
};
typedef struct place place;

struct airportCP {
	int code;
	char *name;
	double lat;
	double lon;
	double distance;
};
typedef struct airportCP airportCP;

struct returnCP {
	int error;
	airportCP array[5];
};
typedef struct returnCP returnCP;

struct coordinateCP {
	double lat;
	double lon;
};
typedef struct coordinateCP coordinateCP;

typedef struct tNode *tNodePtr;

struct tNode {
	tNodePtr array[26];
	int index;
	double lat;
	double lon;
};
typedef struct tNode tNode;

#define PLACES_PROG 0x3232077A
#define PLACES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define callPlaces 1
extern  returnCP * callplaces_1(char *, CLIENT *);
extern  returnCP * callplaces_1_svc(char *, struct svc_req *);
extern int places_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define callPlaces 1
extern  returnCP * callplaces_1();
extern  returnCP * callplaces_1_svc();
extern int places_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_place (XDR *, place*);
extern  bool_t xdr_airportCP (XDR *, airportCP*);
extern  bool_t xdr_returnCP (XDR *, returnCP*);
extern  bool_t xdr_coordinateCP (XDR *, coordinateCP*);
extern  bool_t xdr_tNodePtr (XDR *, tNodePtr*);
extern  bool_t xdr_tNode (XDR *, tNode*);

#else /* K&R C */
extern bool_t xdr_place ();
extern bool_t xdr_airportCP ();
extern bool_t xdr_returnCP ();
extern bool_t xdr_coordinateCP ();
extern bool_t xdr_tNodePtr ();
extern bool_t xdr_tNode ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLIENTPLACES_H_RPCGEN */
