/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ClientPlaces.h"

bool_t
xdr_tNodePtr (XDR *xdrs, tNodePtr *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct tNode), (xdrproc_t) xdr_tNode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_place (XDR *xdrs, place *objp)
{
	register int32_t *buf;

	 if (!xdr_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_state (xdrs, &objp->state))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tNode (XDR *xdrs, tNode *objp)
{
	register int32_t *buf;

	 if (!xdr_tNodePtr (xdrs, &objp->array))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->index))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}
