/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ClientPlaces.h"

list_ret *
call_places_1_svc(name *argp, struct svc_req *rqstp)
{
	printf("Hello.\n");
	static list_ret  result;
	result.err = 0;
	airport test;
	result.list_ret_u.list.placename = "test\n";
	result.list_ret_u.list.airport1 = test;
	result.list_ret_u.list.airport2 = test;
	result.list_ret_u.list.airport3 = test;
	result.list_ret_u.list.airport4 = test;
	result.list_ret_u.list.airport5 = test;
	return &result;
}
