/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ClientPlaces.h"
#include <string>

void
client_places_prog_1(char* host, std::string city, std::string state)
{
	CLIENT *clnt;
	list_ret  *result_1;
	std::string conc = city+state;
	name  call_places_1_arg = const_cast<char*>(conc.c_str());

#ifndef	DEBUG
	clnt = clnt_create (host, CLIENT_PLACES_PROG, CLIENT_PLACES_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = call_places_1(&call_places_1_arg, clnt);
	if (result_1 == (list_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("%s\n", result_1->list_ret_u.list.name);
		printf("code=%s, name=%s, state=%s, distance=%f \n\n", result_1->list_ret_u.list.airport1.code, result_1->list_ret_u.list.airport1.name, result_1->list_ret_u.list.airport1.state, result_1->list_ret_u.list.airport1.dist);
		printf("code=%s, name=%s, state=%s, distance=%f \n\n", result_1->list_ret_u.list.airport2.code, result_1->list_ret_u.list.airport2.name, result_1->list_ret_u.list.airport2.state, result_1->list_ret_u.list.airport2.dist);
		printf("code=%s, name=%s, state=%s, distance=%f \n\n", result_1->list_ret_u.list.airport3.code, result_1->list_ret_u.list.airport3.name, result_1->list_ret_u.list.airport3.state, result_1->list_ret_u.list.airport3.dist);
		printf("code=%s, name=%s, state=%s, distance=%f \n\n", result_1->list_ret_u.list.airport4.code, result_1->list_ret_u.list.airport4.name, result_1->list_ret_u.list.airport4.state, result_1->list_ret_u.list.airport4.dist);
		printf("code=%s, name=%s, state=%s, distance=%f \n\n", result_1->list_ret_u.list.airport5.code, result_1->list_ret_u.list.airport5.name, result_1->list_ret_u.list.airport5.state, result_1->list_ret_u.list.airport5.dist);
	}

	//Free client memory before closing everything.
    clnt_freeres(clnt, (xdrproc_t)xdr_list_ret, result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char* host;
	std::string city;
	std::string state;

	if (argc < 4) {
		printf ("usage: %s placeshost city state\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	city = argv[2];
	state = argv[3];
	client_places_prog_1 (host, city, state);
exit (0);
}
