/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLIENTPLACES_H_RPCGEN
#define _CLIENTPLACES_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct airport {
	int code;
	char *name;
	double lat;
	double lon;
	double distance;
};
typedef struct airport airport;
#ifdef __cplusplus
extern "C" bool_t xdr_airport(XDR *, airport*);
#elif __STDC__
extern  bool_t xdr_airport(XDR *, airport*);
#else /* Old Style C */
bool_t xdr_airport();
#endif /* Old Style C */


struct airportList {
	int error;
	airport array[5];
};
typedef struct airportList airportList;
#ifdef __cplusplus
extern "C" bool_t xdr_airportList(XDR *, airportList*);
#elif __STDC__
extern  bool_t xdr_airportList(XDR *, airportList*);
#else /* Old Style C */
bool_t xdr_airportList();
#endif /* Old Style C */


struct KDNode {
	struct KDNode *right;
	struct KDNode *left;
	double lat;
	double lon;
};
typedef struct KDNode KDNode;
#ifdef __cplusplus
extern "C" bool_t xdr_KDNode(XDR *, KDNode*);
#elif __STDC__
extern  bool_t xdr_KDNode(XDR *, KDNode*);
#else /* Old Style C */
bool_t xdr_KDNode();
#endif /* Old Style C */


struct TrieNode {
	struct TrieNode *TN;
	int index;
	double lat;
	double lon;
};
typedef struct TrieNode TrieNode;
#ifdef __cplusplus
extern "C" bool_t xdr_TrieNode(XDR *, TrieNode*);
#elif __STDC__
extern  bool_t xdr_TrieNode(XDR *, TrieNode*);
#else /* Old Style C */
bool_t xdr_TrieNode();
#endif /* Old Style C */


#define AIRPORT_PROG ((rpc_uint)0x32320776)
#define AIRPORT_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define callPlaces ((rpc_uint)1)
extern "C" airportList * callplaces_1(char *, CLIENT *);
extern "C" airportList * callplaces_1_svc(char *, struct svc_req *);

#elif __STDC__
#define callPlaces ((rpc_uint)1)
extern  airportList * callplaces_1(char *, CLIENT *);
extern  airportList * callplaces_1_svc(char *, struct svc_req *);

#else /* Old Style C */
#define callPlaces ((rpc_uint)1)
extern  airportList * callplaces_1();
extern  airportList * callplaces_1_svc();
#endif /* Old Style C */

#endif /* !_CLIENTPLACES_H_RPCGEN */
