
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT1 = ClientPlaces_client
SERVER1 = ClientPlaces_server

CLIENT2 = PlacesAirport_client
SERVER2 = PlacesAirport_server

SOURCES1_CLNT.c = 
SOURCES1_CLNT.h = 
SOURCES1_SVC.c = 
SOURCES1_SVC.h = 
SOURCES1.x = ClientPlaces.x

SOURCES2_CLNT.c = 
SOURCES2_CLNT.h = 
SOURCES2_SVC.c = 
SOURCES2_SVC.h = 
SOURCES2.x = PlacesAirport.x

TARGETS1_SVC.c = ClientPlaces_svc.c ClientPlaces_server.c ClientPlaces_xdr.c 
TARGETS1_CLNT.c = ClientPlaces_clnt.c ClientPlaces_client.c ClientPlaces_xdr.c 
TARGETS1 = ClientPlaces.h ClientPlaces_xdr.c ClientPlaces_clnt.c ClientPlaces_svc.c ClientPlaces_client.c ClientPlaces_server.c

TARGETS2_SVC.c = PlacesAirport_svc.c PlacesAirport_server.c PlacesAirport_xdr.c 
TARGETS2_CLNT.c = PlacesAirport_clnt.c PlacesAirport_client.c PlacesAirport_xdr.c 
TARGETS2 = PlacesAirport.h PlacesAirport_xdr.c PlacesAirport_clnt.c PlacesAirport_svc.c PlacesAirport_client.c PlacesAirport_server.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g 
LDLIBS += -lnsl
RPCGENFLAGS = 

# Targets 

all : $(CLIENT1) $(SERVER1) $(SERVER2)

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

#place
$(OBJECTS1_CLNT) : $(SOURCES1_CLNT.c) $(SOURCES1_CLNT.h) $(TARGETS1_CLNT.c) 

$(OBJECTS1_SVC) : $(SOURCES1_SVC.c) $(SOURCES1_SVC.h) $(TARGETS1_SVC.c) 

#server
$(OBJECTS2_CLNT) : $(SOURCES2_CLNT.c) $(SOURCES2_CLNT.h) $(TARGETS2_CLNT.c) 

$(OBJECTS2_SVC) : $(SOURCES2_SVC.c) $(SOURCES2_SVC.h) $(TARGETS2_SVC.c) 

#airport client#airport client#airport client
$(CLIENT2) : $(OBJECTS2_CLNT) 
	$(LINK.c) -o $(CLIENT2) $(OBJECTS2_CLNT) $(LDLIBS) 

$(SERVER1) : $(OBJECTS1_SVC) 
	$(LINK.c) -o $(SERVER2) $(OBJECTS2_SVC) $(LDLIBS)

ClientPlaces_client.o : ClientPlaces_client.c
	$(LINK.cc) -std=c++11 -c -o ClientPlaces_client.o ClientPlaces_client.c

ClientPlaces_server.o : ClientPlaces_server.c
	$(LINK.cc) -std=c++11 -c -o ClientPlaces_server.o ClientPlaces_server.c



 clean:
	 $(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER)


