/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "PlacesAirport.h"

airportList *
callairport_1_svc(airport *argp, struct svc_req *rqstp)
{
	static airportList  result;

	/*
	 * insert server code here
	 */

	return &result;
}
