/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACESAIRPORTS_H_RPCGEN
#define _PLACESAIRPORTS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 256

typedef char *name;

typedef char *code;

typedef char *state;

#ifndef AIRPORT
#define AIRPORT
struct airport {
	code code;
	name name;
	state state;
	double lat;
	double lon;
	double dist;
};
typedef struct airport airport;
#endif

#ifndef COORDINATE
#define COORDINATE
struct coordinate {
	double lat;
	double lon;
};
typedef struct coordinate coordinate;
#endif

#ifndef AIRPORTLIST
#define AIRPORTLIST
struct airportList {
	name name;
	coordinate coordinate;
	airport airport1;
	airport airport2;
	airport airport3;
	airport airport4;
	airport airport5;
};
typedef struct airportList airportList;
#endif

#ifndef LIST_RET
#define LIST_RET
struct list_ret {
	int err;
	union {
		airportList list;
	} list_ret_u;
};
typedef struct list_ret list_ret;
#endif

#define PLACES_AIRPORT_PROG 0x66454320
#define PLACES_AIRPORT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALL_AIRPORTS 1
extern  list_ret * call_airports_1(coordinate *, CLIENT *);
extern  list_ret * call_airports_1_svc(coordinate *, struct svc_req *);
extern int places_airport_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALL_AIRPORTS 1
extern  list_ret * call_airports_1();
extern  list_ret * call_airports_1_svc();
extern int places_airport_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_name (XDR *, name*);
extern  bool_t xdr_code (XDR *, code*);
extern  bool_t xdr_state (XDR *, state*);
extern  bool_t xdr_airport (XDR *, airport*);
extern  bool_t xdr_airportList (XDR *, airportList*);
extern  bool_t xdr_list_ret (XDR *, list_ret*);
extern  bool_t xdr_coordinate (XDR *, coordinate*);

#else /* K&R C */
extern bool_t xdr_name ();
extern bool_t xdr_code ();
extern bool_t xdr_state ();
extern bool_t xdr_airport ();
extern bool_t xdr_airportList ();
extern bool_t xdr_list_ret ();
extern bool_t xdr_coordinate ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACESAIRPORTS_H_RPCGEN */
