/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "PlacesAirports.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

list_ret *
call_airports_1(coordinate *argp, CLIENT *clnt)
{
	static list_ret clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CALL_AIRPORTS,
		(xdrproc_t) xdr_coordinate, (caddr_t) argp,
		(xdrproc_t) xdr_list_ret, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
