/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "PlacesAirports.h"

bool_t
xdr_kDNodePtr (XDR *xdrs, kDNodePtr *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct kDNode), (xdrproc_t) xdr_kDNode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_kDNode (XDR *xdrs, kDNode *objp)
{
	register int32_t *buf;

	 if (!xdr_kDNodePtr (xdrs, &objp->right))
		 return FALSE;
	 if (!xdr_kDNodePtr (xdrs, &objp->left))
		 return FALSE;
	 if (!xdr_airport (xdrs, &objp->airport))
		 return FALSE;
	return TRUE;
}
