/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */
#include "PlacesAirports.h"

bool_t
xdr_name (XDR *xdrs, name *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_code (XDR *xdrs, code *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_state (XDR *xdrs, state *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airport (XDR *xdrs, airport *objp)
{
	register int32_t *buf;

	 if (!xdr_code (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_state (xdrs, &objp->state))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->dist))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportList (XDR *xdrs, airportList *objp)
{
	register int32_t *buf;

	 if (!xdr_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_coordinate (xdrs, &objp->coordinate))
		 return FALSE;
	 if (!xdr_airport (xdrs, &objp->airport1))
		 return FALSE;
	 if (!xdr_airport (xdrs, &objp->airport2))
		 return FALSE;
	 if (!xdr_airport (xdrs, &objp->airport3))
		 return FALSE;
	 if (!xdr_airport (xdrs, &objp->airport4))
		 return FALSE;
	 if (!xdr_airport (xdrs, &objp->airport5))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_list_ret (XDR *xdrs, list_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_airportList (xdrs, &objp->list_ret_u.list))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_coordinate (XDR *xdrs, coordinate *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}
