/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ClientPlaces.h"


void
client_places_prog_1(char *host)
{
	CLIENT *clnt;
	returnCP  *result_1;
	nametypecp  callplaces_1_arg = host;

#ifndef	DEBUG
	clnt = clnt_create (host, CLIENT_PLACES_PROG, CLIENT_PLACES_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = callplaces_1(&callplaces_1_arg, clnt);
	if (result_1 == (returnCP *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		if(result_1->err==0){
			printf("%s\n", result_1->returnCP_u.list->airport.code);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	client_places_prog_1 (host);
exit (0);
}
