/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ClientPlaces.h"

bool_t
xdr_nametypecp (XDR *xdrs, nametypecp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_statetypecp (XDR *xdrs, statetypecp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_codetypecp (XDR *xdrs, codetypecp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 5))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportListCP (XDR *xdrs, airportListCP *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct airportNodeCP), (xdrproc_t) xdr_airportNodeCP))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tNodePtr (XDR *xdrs, tNodePtr *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct tNode), (xdrproc_t) xdr_tNode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_place (XDR *xdrs, place *objp)
{
	register int32_t *buf;

	 if (!xdr_nametypecp (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_statetypecp (xdrs, &objp->state))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportCP (XDR *xdrs, airportCP *objp)
{
	register int32_t *buf;

	 if (!xdr_codetypecp (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_nametypecp (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->distance))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportNodeCP (XDR *xdrs, airportNodeCP *objp)
{
	register int32_t *buf;

	 if (!xdr_airportCP (xdrs, &objp->airport))
		 return FALSE;
	 if (!xdr_airportListCP (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_returnCP (XDR *xdrs, returnCP *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_airportListCP (xdrs, &objp->returnCP_u.list))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_tNode (XDR *xdrs, tNode *objp)
{
	register int32_t *buf;

	 if (!xdr_tNodePtr (xdrs, &objp->array))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->index))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}
