/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "PlacesAirports.h"

returnPA *
callairports_1_svc(coordinate *argp, struct svc_req *rqstp)
{
	static returnPA  result;

	/*
	 * insert server code here
	 */

	return &result;
}
