/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "PlacesAirports.h"

bool_t
xdr_nametypepa (XDR *xdrs, nametypepa *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, NAMETYPEPASIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_codetypepa (XDR *xdrs, codetypepa *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, CODETYPEPASIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportListPA (XDR *xdrs, airportListPA *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct airportNodePA), (xdrproc_t) xdr_airportNodePA))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_kDNodePtr (XDR *xdrs, kDNodePtr *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct kDNode), (xdrproc_t) xdr_kDNode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportPA (XDR *xdrs, airportPA *objp)
{
	register int32_t *buf;

	 if (!xdr_codetypepa (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_nametypepa (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->distance))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportNodePA (XDR *xdrs, airportNodePA *objp)
{
	register int32_t *buf;

	 if (!xdr_airportPA (xdrs, &objp->airport))
		 return FALSE;
	 if (!xdr_airportListPA (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_returnPA (XDR *xdrs, returnPA *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_airportListPA (xdrs, &objp->returnPA_u.list))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_coordinate (XDR *xdrs, coordinate *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_kDNode (XDR *xdrs, kDNode *objp)
{
	register int32_t *buf;

	 if (!xdr_kDNodePtr (xdrs, &objp->right))
		 return FALSE;
	 if (!xdr_kDNodePtr (xdrs, &objp->left))
		 return FALSE;
	 if (!xdr_airportPA (xdrs, &objp->airport))
		 return FALSE;
	return TRUE;
}
