/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACESAIRPORTS_H_RPCGEN
#define _PLACESAIRPORTS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define NAMETYPEPASIZE 256
#define CODETYPEPASIZE 3

typedef char *nametypepa;

typedef char *codetypepa;

typedef struct airportNodePA *airportListPA;

typedef struct kDNode *kDNodePtr;

struct airportPA {
	codetypepa code;
	nametypepa name;
	double lat;
	double lon;
	double distance;
};
typedef struct airportPA airportPA;

struct airportNodePA {
	airportPA airport;
	airportListPA next;
};
typedef struct airportNodePA airportNodePA;

struct returnPA {
	int err;
	union {
		airportListPA list;
	} returnPA_u;
};
typedef struct returnPA returnPA;

struct coordinate {
	double lat;
	double lon;
};
typedef struct coordinate coordinate;

struct kDNode {
	kDNodePtr right;
	kDNodePtr left;
	airportPA airport;
};
typedef struct kDNode kDNode;

#define PLACES_AIRPORT_PROG 0x51320780
#define PLACES_AIRPORT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALLAIRPORTS 1
extern  returnPA * callairports_1(coordinate *, CLIENT *);
extern  returnPA * callairports_1_svc(coordinate *, struct svc_req *);
extern int places_airport_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALLAIRPORTS 1
extern  returnPA * callairports_1();
extern  returnPA * callairports_1_svc();
extern int places_airport_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametypepa (XDR *, nametypepa*);
extern  bool_t xdr_codetypepa (XDR *, codetypepa*);
extern  bool_t xdr_airportListPA (XDR *, airportListPA*);
extern  bool_t xdr_kDNodePtr (XDR *, kDNodePtr*);
extern  bool_t xdr_airportPA (XDR *, airportPA*);
extern  bool_t xdr_airportNodePA (XDR *, airportNodePA*);
extern  bool_t xdr_returnPA (XDR *, returnPA*);
extern  bool_t xdr_coordinate (XDR *, coordinate*);
extern  bool_t xdr_kDNode (XDR *, kDNode*);

#else /* K&R C */
extern bool_t xdr_nametypepa ();
extern bool_t xdr_codetypepa ();
extern bool_t xdr_airportListPA ();
extern bool_t xdr_kDNodePtr ();
extern bool_t xdr_airportPA ();
extern bool_t xdr_airportNodePA ();
extern bool_t xdr_returnPA ();
extern bool_t xdr_coordinate ();
extern bool_t xdr_kDNode ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACESAIRPORTS_H_RPCGEN */
